

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Pdchaudhary\LokaliseTranslateBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Pdchaudhary\LokaliseTranslateBundle\Service\:
        resource: '../../Service'
        public: true

    Pdchaudhary\LokaliseTranslateBundle\Command\:
        resource: '../../Command'
        public: true
    
    Pdchaudhary\LokaliseTranslateBundle\Installer:
        public: true
        arguments:   
            $bundle: "@=service('kernel').getBundle('LokaliseTranslateBundle')"

    Pdchaudhary\LokaliseTranslateBundle\EventListener\ObjectListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }
    
    Pdchaudhary\LokaliseTranslateBundle\EventListener\DocumentListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: pimcore.document.postUpdate, method: onPostUpdate }


    
        

# add more services, or override services that need manual wiring
#    Pdchaudhary\LokaliseTranslateBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
